meta_product_name: "クラログ"
meta_title: "クラログ - 登る、記録する、うまくなる！"
meta_description: "ボルダリングジム、クライミングジムで登った記録も、岩場で登った記録もまとめて管理。登った本数やグレードの推移などもひと目で確認！"
meta_image: "climbing-log-image.jpg" # should exist in `app/assets/images/`
twitter_account: "@climbing_log"   # required for Twitter Cards
